# Packages
packages:core:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/*
          - packages/core/**/*
packages:create-app:
  - changed-files:
      - any-glob-to-any-file:
          - packages/create-app/*
          - packages/create-app/**/*
packages:cli:
  - changed-files:
      - any-glob-to-any-file:
          - packages/cli/*
          - packages/cli/**/*
packages:formatters:
  - changed-files:
      - any-glob-to-any-file:
          - packages/formatters/*
          - packages/formatters/**/*

# Apps
apps:website:
  - changed-files:
      - any-glob-to-any-file:
          - apps/website/*
          - apps/website/**/*
