name: Label Sync
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'

permissions:
  issues: write

jobs:
  label-sync:
    name: Label Sync
    runs-on: ubuntu-latest
    if: github.repository_owner == 'wwebjs'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Label sync
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
